default_agent: my_agent
agents:
  my_agent:
    name: my_agent
    entrypoint: my_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::118019414362:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e72c1a7c7a
      execution_role_auto_create: false
      account: '118019414362'
      region: us-east-1
      ecr_repository: 118019414362.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-my_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: my_agent-IxZ13AH2BR
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:118019414362:runtime/my_agent-IxZ13AH2BR
      agent_session_id: b6bb4b4d-1dcd-4def-90ab-578a5a93e2a0
    codebuild:
      project_name: bedrock-agentcore-my_agent-builder
      execution_role: arn:aws:iam::118019414362:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e72c1a7c7a
      source_bucket: bedrock-agentcore-codebuild-sources-118019414362-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: my_agent_mem-t2HKAnFhUD
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:118019414362:memory/my_agent_mem-t2HKAnFhUD
      memory_name: my_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
